services:
  api-server:
    build: .
    container_name: multi-persistence-backend-api-server
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      MONGO_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      TZ: Europe/Rome
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: 'curl -f http://localhost:8080/actuator/health -H "Connection: close" || exit 1'
      interval: 5s
      retries: 10

  newman:
    image: postman/newman
    profiles:
      - test-newman
    working_dir: /etc/newman
    volumes:
      - ./postman:/etc/newman
    entrypoint: >
      sh -c '
        echo "Checking whether the API is already running...";
        if ! wget -q -O - http://api-server:8080/actuator/health | grep -q "\"status\":\"UP\""; then
          echo "";
          echo "The API server is not available or not healthy.";
          echo "Please start the application first, then run the Newman tests again.";
          exit 1;
        fi;
        echo "API is healthy. Starting Newman tests...";
        newman run newman_test_collection.json --env-var baseUrl=http://api-server:8080
      '