spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/sql_vs_nosql_postgres_db

  data:
    mongodb:
      uri: mongodb://mongo-admin:mongo-psw@mongo:27017/sql_vs_nosql_mongo_db?authSource=admin